import { type ArgsDef, type CommandDef, defineCommand, renderUsage } from "citty";

import { CLI_VERSION } from "./cliCommandTypes.ts";

export const topLevelCommandNames = ["serve", "restart", "bridge", "artifacts", "help"] as const;
export const bridgeActionNames = ["pair", "proxy", "codex", "terminal", "claude"] as const;
export const artifactActionNames = ["list", "build", "download", "pull"] as const;

const helpAndVersionArgs = {
	help: {
		type: "boolean",
		alias: "h",
		description: "Show command help and exit.",
	},
	version: {
		type: "boolean",
		alias: "V",
		description: "Show the Couchview version and exit.",
	},
} as const satisfies ArgsDef;

const rootServeArgs = {
	...helpAndVersionArgs,
	repo: {
		type: "string",
		alias: "r",
		valueHint: "path",
		description: "Local repository path to serve.",
	},
	host: {
		type: "string",
		alias: "H",
		valueHint: "address",
		description: "Bind address (default: 127.0.0.1).",
	},
	port: {
		type: "string",
		alias: "p",
		valueHint: "number",
		description: "HTTP port from 1 to 65535 (default: 4173).",
	},
	interactive: {
		type: "boolean",
		alias: "i",
		description: "Prompt for omitted startup settings before serving.",
	},
	"enable-terminal": {
		type: "boolean",
		description: "Enable browser terminal access, including beyond loopback.",
	},
	"disable-terminal": {
		type: "boolean",
		description: "Disable browser terminal access.",
	},
	"enable-speech": {
		type: "boolean",
		description: "Enable host-run FluidAudio speech transcription (macOS ARM64).",
	},
	"disable-speech": {
		type: "boolean",
		description: "Disable host-run speech transcription.",
	},
	"enable-voice-commands": {
		type: "boolean",
		description: "Install and enable local Needle 2 voice-command interpretation.",
	},
	"enable-terminal-p2p": {
		type: "boolean",
		description: "Opt into direct terminal P2P transport and IP disclosure.",
	},
	"disable-terminal-p2p": {
		type: "boolean",
		description: "Force terminal traffic to use the protected WebSocket.",
	},
	"enable-remote-bridge": {
		type: "boolean",
		description: "Enable paired native IDE connections to loopback SSH.",
	},
	"disable-remote-bridge": {
		type: "boolean",
		description: "Disable native IDE bridge access.",
	},
	"enable-remote-bridge-p2p": {
		type: "boolean",
		description: "Opt into direct IDE WebRTC transport and IP disclosure.",
	},
	"disable-remote-bridge-p2p": {
		type: "boolean",
		description: "Force native IDE traffic through the protected WebSocket.",
	},
	"remote-bridge-origin-access": {
		type: "string",
		valueHint: "provider",
		description: "Origin-access provider in bridge pairings (default: auto).",
	},
} as const satisfies ArgsDef;

export const defaultServeArgs = rootServeArgs;
export const explicitServeArgs = {
	...rootServeArgs,
	repository: {
		type: "positional",
		required: false,
		valueHint: "path",
		description: "Repository directory.",
	},
} as const satisfies ArgsDef;

export const restartArgs = {
	...helpAndVersionArgs,
	host: rootServeArgs.host,
	port: rootServeArgs.port,
} as const satisfies ArgsDef;

export const bridgeCommandArgs = helpAndVersionArgs;

export const bridgePairArgs = {
	...helpAndVersionArgs,
	url: {
		type: "string",
		valueHint: "origin",
		description: "Couchview public origin from the pairing command.",
		required: true,
	},
	code: {
		type: "string",
		valueHint: "code",
		description: "One-use pairing code generated by Couchview.",
		required: true,
	},
	"origin-access": {
		type: "string",
		valueHint: "provider",
		description: "Origin-access provider for HTTP and WebSocket setup.",
	},
} as const satisfies ArgsDef;

export const bridgeProxyArgs = {
	...helpAndVersionArgs,
	profile: {
		type: "string",
		valueHint: "id",
		description: "Saved bridge profile ID.",
		required: true,
	},
} as const satisfies ArgsDef;

const bridgeConnectionArgs = {
	...helpAndVersionArgs,
	profile: {
		type: "string",
		valueHint: "id-or-host",
		description: "Saved bridge profile ID or managed SSH host alias.",
	},
	repo: {
		type: "string",
		alias: "r",
		valueHint: "absolute-path",
		description: "Absolute repository path on the paired host.",
	},
} as const satisfies ArgsDef;

export const bridgeCodexArgs = bridgeConnectionArgs;
export const bridgeTerminalArgs = bridgeConnectionArgs;
export const bridgeClaudeArgs = bridgeConnectionArgs;

const artifactLocationArgs = {
	...helpAndVersionArgs,
	repo: {
		type: "string",
		alias: "r",
		valueHint: "path",
		description: "Local checkout used to match a registered repository.",
	},
	profile: {
		type: "string",
		valueHint: "id-or-host",
		description: "Saved bridge profile ID or managed SSH host alias.",
	},
	repository: {
		type: "string",
		valueHint: "id-or-name",
		description: "Stable server repository ID or unique repository name.",
	},
	json: {
		type: "boolean",
		description: "Print structured JSON; live build logs use stderr.",
	},
} as const satisfies ArgsDef;

const artifactNameArg = {
	name: {
		type: "positional",
		valueHint: "name",
		description: "Artifact definition name.",
		required: true,
	},
} as const satisfies ArgsDef;

const artifactOutputArgs = {
	output: {
		type: "string",
		alias: "o",
		valueHint: "file",
		description: "Write the download to this file.",
	},
	force: {
		type: "boolean",
		alias: "f",
		description: "Replace an existing output file.",
	},
} as const satisfies ArgsDef;

export const artifactListArgs = artifactLocationArgs;
export const artifactBuildArgs = {
	...artifactLocationArgs,
	...artifactNameArg,
} as const satisfies ArgsDef;
export const artifactDownloadArgs = {
	...artifactLocationArgs,
	...artifactNameArg,
	build: {
		type: "string",
		valueHint: "id",
		description: "Download a specific retained build ID.",
	},
	...artifactOutputArgs,
} as const satisfies ArgsDef;
export const artifactPullArgs = {
	...artifactLocationArgs,
	...artifactNameArg,
	...artifactOutputArgs,
} as const satisfies ArgsDef;

export const helpCommandArgs = {
	...helpAndVersionArgs,
	command: {
		type: "positional",
		required: false,
		description: "Top-level command.",
	},
	subcommand: {
		type: "positional",
		required: false,
		description: "Bridge or artifact action.",
	},
} as const satisfies ArgsDef;

const bridgePairCommand = defineCommand({
	meta: { name: "pair", description: "Pair this computer with a Couchview server." },
	args: bridgePairArgs,
});
const bridgeProxyCommand = defineCommand({
	meta: {
		name: "proxy",
		description: "Internal OpenSSH ProxyCommand transport; invoked automatically.",
	},
	args: bridgeProxyArgs,
});
const bridgeCodexCommand = defineCommand({
	meta: { name: "codex", description: "Run Codex against a paired remote repository." },
	args: bridgeCodexArgs,
});
const bridgeTerminalCommand = defineCommand({
	meta: { name: "terminal", description: "Open a paired remote repository shell." },
	args: bridgeTerminalArgs,
});
const bridgeClaudeCommand = defineCommand({
	meta: { name: "claude", description: "Start Claude Code Remote Control remotely." },
	args: bridgeClaudeArgs,
});

const bridgeCommand = defineCommand({
	meta: { name: "bridge", description: "Pair or connect development tools through SSH." },
	args: bridgeCommandArgs,
	subCommands: {
		pair: bridgePairCommand,
		proxy: bridgeProxyCommand,
		codex: bridgeCodexCommand,
		terminal: bridgeTerminalCommand,
		claude: bridgeClaudeCommand,
	},
});

const artifactListCommand = defineCommand({
	meta: { name: "list", description: "List artifact definitions and retained builds." },
	args: artifactListArgs,
});
const artifactBuildCommand = defineCommand({
	meta: { name: "build", description: "Build an artifact and stream its logs." },
	args: artifactBuildArgs,
});
const artifactDownloadCommand = defineCommand({
	meta: { name: "download", description: "Download a retained successful build." },
	args: artifactDownloadArgs,
});
const artifactPullCommand = defineCommand({
	meta: { name: "pull", description: "Build and download one exact snapshot." },
	args: artifactPullArgs,
});

const artifactsCommand = defineCommand({
	meta: { name: "artifacts", description: "Build and download repository artifacts." },
	args: bridgeCommandArgs,
	subCommands: {
		list: artifactListCommand,
		build: artifactBuildCommand,
		download: artifactDownloadCommand,
		pull: artifactPullCommand,
	},
});

const serveCommand = defineCommand({
	meta: { name: "serve", description: "Start Couchview or add a repository." },
	args: explicitServeArgs,
});

const restartCommand = defineCommand({
	meta: { name: "restart", description: "Rebuild and restart the production server." },
	args: restartArgs,
});

const helpCommand = defineCommand({
	meta: { name: "help", description: "Show general or command-specific help." },
	args: helpCommandArgs,
});

const rootCommand = defineCommand({
	meta: {
		name: "couchview",
		version: CLI_VERSION,
		description: "A local-first Git diff review PWA powered by Bun.",
	},
	args: defaultServeArgs,
	default: "serve",
	subCommands: {
		serve: serveCommand,
		restart: restartCommand,
		bridge: bridgeCommand,
		artifacts: artifactsCommand,
		help: helpCommand,
	},
});

const definitions = new Map<string, CommandDef<any>>([
	["", rootCommand],
	["serve", serveCommand],
	["restart", restartCommand],
	["bridge", bridgeCommand],
	["bridge pair", bridgePairCommand],
	["bridge proxy", bridgeProxyCommand],
	["bridge codex", bridgeCodexCommand],
	["bridge terminal", bridgeTerminalCommand],
	["bridge claude", bridgeClaudeCommand],
	["artifacts", artifactsCommand],
	["artifacts list", artifactListCommand],
	["artifacts build", artifactBuildCommand],
	["artifacts download", artifactDownloadCommand],
	["artifacts pull", artifactPullCommand],
	["help", helpCommand],
]);

const helpDetails = new Map<string, string>([
	["", "Without a command, Couchview starts the server using these options."],
	[
		"serve",
		`Environment:
  COUCHVIEW_ROOT           Default repository path.
  COUCHVIEW_HOST           Default bind address (default: 127.0.0.1).
  PORT                     Default HTTP port (default: 4173).
  COUCHVIEW_TERMINAL       Set terminal access to 1 or 0.
  COUCHVIEW_TERMINAL_P2P   Set direct terminal P2P to 1 or 0.
  COUCHVIEW_TERMINAL_STUN  One to four comma-separated STUN URLs.
  COUCHVIEW_ENABLE_SPEECH  Set host-run speech transcription to 1 or 0.
  COUCHVIEW_REMOTE_BRIDGE  Set native IDE bridge access to 1 or 0.
  COUCHVIEW_REMOTE_BRIDGE_P2P
                           Set direct IDE WebRTC transport to 1 or 0.
  COUCHVIEW_REMOTE_BRIDGE_STUN
                           One to four comma-separated STUN URLs.
  COUCHVIEW_REMOTE_BRIDGE_PORT
                           Loopback SSH port (default: 22).
  COUCHVIEW_REMOTE_BRIDGE_ORIGIN_ACCESS
                           Pairing origin-access provider (default: auto).
  COUCHVIEW_ALLOWED_ORIGINS
                           Trusted reverse-proxy origins; no wildcards.
  STATIC_DIR               Override the production asset directory.

Examples:
  couchview
  couchview --repo ../project --port 4173
  couchview serve ../project --port 4173
  couchview --interactive
  couchview --host 0.0.0.0 --enable-terminal

Security:
  Binding beyond loopback exposes repository controls to the network. Terminal
  access controls tmux with your OS-user permissions; direct P2P can disclose
  peer addresses and sends terminal payloads outside a configured proxy. The
  native bridge is separately paired and can only reach loopback SSH.`,
	],
	[
		"restart",
		`Environment:
  COUCHVIEW_HOST  Default server address (default: 127.0.0.1).
  PORT            Default server port (default: 4173).

Example:
  couchview restart --host 127.0.0.1 --port 4173`,
	],
	[
		"bridge",
		`Pair stores a private device credential and installs a managed OpenSSH host alias.
Proxy is invoked automatically by OpenSSH and must not be run interactively. One
pairing can open every repository registered on that Couchview host. Verify the
managed host with plain ssh first; normal SSH host-key and login checks apply.`,
	],
	[
		"bridge proxy",
		`Generated SSH configuration launches this command automatically. Do not run
it manually; use the managed SSH host alias created by bridge pair instead.`,
	],
	["bridge codex", "Arguments after '--' are passed unchanged to Codex."],
	["bridge claude", "Arguments after '--' are passed unchanged to Claude Code Remote Control."],
	[
		"artifacts",
		`Without --profile, Couchview uses an already-running local server and matches
the Git checkout containing the current directory or --repo. It never starts a
server implicitly. With --profile, it uses the selected paired host. Downloads
are verified and never overwrite unless --force is set.`,
	],
	[
		"help",
		`Examples:
  couchview help serve
  couchview help bridge pair
  couchview artifacts download --help`,
	],
]);

export function cliHelpPathExists(path: readonly string[]): boolean {
	return definitions.has(path.join(" "));
}

function usageParent(path: readonly string[]): CommandDef<any> | undefined {
	if (path.length === 0) return undefined;
	const name = ["couchview", ...path.slice(0, -1)].join(" ");
	return defineCommand({ meta: { name, version: CLI_VERSION } });
}

export async function renderCliHelp(path: readonly string[]): Promise<string> {
	const key = path.join(" ");
	const command = definitions.get(key);
	if (!command) throw new Error(`Unknown CLI help path: ${key}`);
	const renderedUsage = await renderUsage(command, usageParent(path));
	const commandAlternatives = topLevelCommandNames.join("|");
	const usage = key
		? renderedUsage
		: renderedUsage.replace(commandAlternatives, `[${commandAlternatives}]`);
	const details = helpDetails.get(key);
	return details ? `${usage}\n\n${details}` : usage;
}
