import type { CliCommandName, CompletionShell } from "./cliCommandTypes.ts";

export type CliOptionType = "boolean" | "string";

export interface CliOptionDefinition {
	name: string;
	short?: string;
	type: CliOptionType;
	valueName?: string;
	description: string;
	commands: readonly CliCommandName[];
	completion?: "directory";
}

export const commandNames = ["serve", "restart", "completion", "bridge", "help"] as const;
export const completionShells: readonly CompletionShell[] = ["zsh", "bash", "fish"];

export const optionDefinitions: readonly CliOptionDefinition[] = [
	{
		name: "help",
		short: "h",
		type: "boolean",
		description: "Show command help and exit.",
		commands: ["serve", "restart", "completion", "bridge"],
	},
	{
		name: "version",
		short: "V",
		type: "boolean",
		description: "Show the Couchview version and exit.",
		commands: ["serve", "restart", "completion", "bridge"],
	},
	{
		name: "install",
		type: "boolean",
		description: "Install Fish completion in the standard per-user directory.",
		commands: ["completion"],
	},
	{
		name: "repo",
		short: "r",
		type: "string",
		valueName: "path",
		description: "Repository path to serve or open through the native bridge.",
		commands: ["serve", "bridge"],
		completion: "directory",
	},
	{
		name: "host",
		short: "H",
		type: "string",
		valueName: "address",
		description: "Bind address (default: 127.0.0.1).",
		commands: ["serve", "restart"],
	},
	{
		name: "port",
		short: "p",
		type: "string",
		valueName: "number",
		description: "HTTP port from 1 to 65535 (default: 4173).",
		commands: ["serve", "restart"],
	},
	{
		name: "interactive",
		short: "i",
		type: "boolean",
		description: "Prompt for omitted startup settings before serving.",
		commands: ["serve"],
	},
	{
		name: "enable-terminal",
		type: "boolean",
		description: "Enable browser terminal access, including beyond loopback.",
		commands: ["serve"],
	},
	{
		name: "disable-terminal",
		type: "boolean",
		description: "Disable browser terminal access.",
		commands: ["serve"],
	},
	{
		name: "enable-terminal-p2p",
		type: "boolean",
		description: "Opt into direct terminal P2P transport and IP disclosure.",
		commands: ["serve"],
	},
	{
		name: "disable-terminal-p2p",
		type: "boolean",
		description: "Force terminal traffic to use the protected WebSocket.",
		commands: ["serve"],
	},
	{
		name: "enable-remote-bridge",
		type: "boolean",
		description: "Enable paired native IDE connections to loopback SSH.",
		commands: ["serve"],
	},
	{
		name: "disable-remote-bridge",
		type: "boolean",
		description: "Disable native IDE bridge access.",
		commands: ["serve"],
	},
	{
		name: "enable-remote-bridge-p2p",
		type: "boolean",
		description: "Opt into direct IDE WebRTC transport and IP disclosure.",
		commands: ["serve"],
	},
	{
		name: "disable-remote-bridge-p2p",
		type: "boolean",
		description: "Force native IDE traffic through the protected WebSocket.",
		commands: ["serve"],
	},
	{
		name: "remote-bridge-origin-access",
		type: "string",
		valueName: "provider",
		description: "Origin-access provider in bridge pairings (default: auto).",
		commands: ["serve"],
	},
	{
		name: "url",
		type: "string",
		valueName: "origin",
		description: "Couchview public origin from the pairing command.",
		commands: ["bridge"],
	},
	{
		name: "code",
		type: "string",
		valueName: "code",
		description: "One-use pairing code generated by Couchview.",
		commands: ["bridge"],
	},
	{
		name: "profile",
		type: "string",
		valueName: "id-or-host",
		description: "Saved bridge profile ID or managed SSH host alias.",
		commands: ["bridge"],
	},
	{
		name: "origin-access",
		type: "string",
		valueName: "provider",
		description: "Origin-access provider for HTTP and WebSocket setup.",
		commands: ["bridge"],
	},
	{
		name: "cloudflare-access",
		type: "boolean",
		description: "Legacy alias for --origin-access cloudflare-access.",
		commands: ["bridge"],
	},
] as const;

export function optionsFor(command: CliCommandName): CliOptionDefinition[] {
	return optionDefinitions.filter((option) => option.commands.includes(command));
}

function editDistance(left: string, right: string): number {
	const previous = Array.from({ length: right.length + 1 }, (_, index) => index);
	for (let leftIndex = 1; leftIndex <= left.length; leftIndex += 1) {
		const current = [leftIndex];
		for (let rightIndex = 1; rightIndex <= right.length; rightIndex += 1) {
			current[rightIndex] = Math.min(
				(current[rightIndex - 1] ?? 0) + 1,
				(previous[rightIndex] ?? 0) + 1,
				(previous[rightIndex - 1] ?? 0) + (left[leftIndex - 1] === right[rightIndex - 1] ? 0 : 1),
			);
		}
		previous.splice(0, previous.length, ...current);
	}
	return previous[right.length] ?? Number.POSITIVE_INFINITY;
}

export function nearestValue(value: string, candidates: readonly string[]): string | null {
	let nearest: string | null = null;
	let nearestDistance = Number.POSITIVE_INFINITY;
	let nearestPrefixLength = -1;
	for (const candidate of candidates) {
		const normalizedValue = value.toLowerCase();
		const normalizedCandidate = candidate.toLowerCase();
		const distance = editDistance(normalizedValue, normalizedCandidate);
		let prefixLength = 0;
		while (
			normalizedValue[prefixLength] !== undefined &&
			normalizedValue[prefixLength] === normalizedCandidate[prefixLength]
		) {
			prefixLength += 1;
		}
		if (
			distance < nearestDistance ||
			(distance === nearestDistance && prefixLength > nearestPrefixLength)
		) {
			nearest = candidate;
			nearestDistance = distance;
			nearestPrefixLength = prefixLength;
		}
	}
	if (!nearest) return null;
	const comparisonLength = Math.max(value.length, nearest.length);
	return nearestDistance <= 2 && nearestDistance <= Math.ceil(comparisonLength / 3)
		? nearest
		: null;
}
