/**
 * Language detection and on-demand grammar loading for the diff engine.
 *
 * The extension map is a curated subset of the mapping maintained by the
 * Pierre diff project (Apache-2.0); shiki language ids are used so each
 * detected language maps directly to an `@shikijs/langs` subpath export.
 * Unknown files fall back to plain text.
 */

export type GrammarLoader = () => Promise<
	Parameters<import("shiki/core").HighlighterCore["loadLanguage"]>[0]
>;

const GRAMMAR_IMPORTS: Record<string, GrammarLoader> = {
	astro: () => import("@shikijs/langs/astro"),
	bash: () => import("@shikijs/langs/bash"),
	bat: () => import("@shikijs/langs/bat"),
	c: () => import("@shikijs/langs/c"),
	clojure: () => import("@shikijs/langs/clojure"),
	cmake: () => import("@shikijs/langs/cmake"),
	coffeescript: () => import("@shikijs/langs/coffeescript"),
	cpp: () => import("@shikijs/langs/cpp"),
	csharp: () => import("@shikijs/langs/csharp"),
	css: () => import("@shikijs/langs/css"),
	csv: () => import("@shikijs/langs/csv"),
	dart: () => import("@shikijs/langs/dart"),
	diff: () => import("@shikijs/langs/diff"),
	dockerfile: () => import("@shikijs/langs/dockerfile"),
	dotenv: () => import("@shikijs/langs/dotenv"),
	elixir: () => import("@shikijs/langs/elixir"),
	elm: () => import("@shikijs/langs/elm"),
	erlang: () => import("@shikijs/langs/erlang"),
	fsharp: () => import("@shikijs/langs/fsharp"),
	gherkin: () => import("@shikijs/langs/gherkin"),
	go: () => import("@shikijs/langs/go"),
	graphql: () => import("@shikijs/langs/graphql"),
	groovy: () => import("@shikijs/langs/groovy"),
	haskell: () => import("@shikijs/langs/haskell"),
	hcl: () => import("@shikijs/langs/hcl"),
	html: () => import("@shikijs/langs/html"),
	ini: () => import("@shikijs/langs/ini"),
	java: () => import("@shikijs/langs/java"),
	javascript: () => import("@shikijs/langs/javascript"),
	jinja: () => import("@shikijs/langs/jinja"),
	json: () => import("@shikijs/langs/json"),
	json5: () => import("@shikijs/langs/json5"),
	jsonc: () => import("@shikijs/langs/jsonc"),
	jsonl: () => import("@shikijs/langs/jsonl"),
	jsx: () => import("@shikijs/langs/jsx"),
	julia: () => import("@shikijs/langs/julia"),
	kotlin: () => import("@shikijs/langs/kotlin"),
	latex: () => import("@shikijs/langs/latex"),
	less: () => import("@shikijs/langs/less"),
	lua: () => import("@shikijs/langs/lua"),
	make: () => import("@shikijs/langs/make"),
	markdown: () => import("@shikijs/langs/markdown"),
	mdx: () => import("@shikijs/langs/mdx"),
	nginx: () => import("@shikijs/langs/nginx"),
	nim: () => import("@shikijs/langs/nim"),
	nix: () => import("@shikijs/langs/nix"),
	"objective-c": () => import("@shikijs/langs/objective-c"),
	ocaml: () => import("@shikijs/langs/ocaml"),
	pascal: () => import("@shikijs/langs/pascal"),
	perl: () => import("@shikijs/langs/perl"),
	php: () => import("@shikijs/langs/php"),
	postcss: () => import("@shikijs/langs/postcss"),
	powershell: () => import("@shikijs/langs/powershell"),
	prisma: () => import("@shikijs/langs/prisma"),
	protobuf: () => import("@shikijs/langs/protobuf"),
	pug: () => import("@shikijs/langs/pug"),
	python: () => import("@shikijs/langs/python"),
	r: () => import("@shikijs/langs/r"),
	regexp: () => import("@shikijs/langs/regexp"),
	ruby: () => import("@shikijs/langs/ruby"),
	rust: () => import("@shikijs/langs/rust"),
	sass: () => import("@shikijs/langs/sass"),
	scala: () => import("@shikijs/langs/scala"),
	scss: () => import("@shikijs/langs/scss"),
	shellscript: () => import("@shikijs/langs/shellscript"),
	solidity: () => import("@shikijs/langs/solidity"),
	sql: () => import("@shikijs/langs/sql"),
	stylus: () => import("@shikijs/langs/stylus"),
	svelte: () => import("@shikijs/langs/svelte"),
	swift: () => import("@shikijs/langs/swift"),
	systemd: () => import("@shikijs/langs/systemd"),
	tcl: () => import("@shikijs/langs/tcl"),
	terraform: () => import("@shikijs/langs/terraform"),
	tex: () => import("@shikijs/langs/tex"),
	toml: () => import("@shikijs/langs/toml"),
	tsv: () => import("@shikijs/langs/tsv"),
	tsx: () => import("@shikijs/langs/tsx"),
	typescript: () => import("@shikijs/langs/typescript"),
	vim: () => import("@shikijs/langs/vim"),
	vue: () => import("@shikijs/langs/vue"),
	xml: () => import("@shikijs/langs/xml"),
	yaml: () => import("@shikijs/langs/yaml"),
	zig: () => import("@shikijs/langs/zig"),
};

const EXTENSION_TO_LANGUAGE: Record<string, string> = {
	asm: "c",
	astro: "astro",
	bash: "shellscript",
	bib: "latex",
	c: "c",
	cc: "cpp",
	cfg: "ini",
	cjs: "javascript",
	clj: "clojure",
	cljc: "clojure",
	cljs: "clojure",
	cmake: "cmake",
	coffee: "coffeescript",
	cpp: "cpp",
	cr: "crystal",
	cs: "csharp",
	css: "css",
	csv: "csv",
	cue: "text",
	cxx: "cpp",
	dart: "dart",
	diff: "diff",
	env: "dotenv",
	erl: "erlang",
	ex: "elixir",
	exs: "elixir",
	feature: "gherkin",
	fish: "shellscript",
	fs: "fsharp",
	fsi: "fsharp",
	fsx: "fsharp",
	gd: "text",
	gem: "text",
	glsl: "text",
	go: "go",
	gql: "graphql",
	graphql: "graphql",
	groovy: "groovy",
	haml: "text",
	handlebars: "text",
	hbs: "text",
	hcl: "hcl",
	hpp: "cpp",
	hrl: "erlang",
	hs: "haskell",
	htm: "html",
	html: "html",
	ini: "ini",
	java: "java",
	jl: "julia",
	js: "javascript",
	json: "json",
	json5: "json5",
	jsonc: "jsonc",
	jsonl: "jsonl",
	jsx: "jsx",
	kt: "kotlin",
	kts: "kotlin",
	less: "less",
	lhs: "haskell",
	liquid: "text",
	lua: "lua",
	m: "objective-c",
	md: "markdown",
	mdx: "mdx",
	mjs: "javascript",
	mm: "objective-c",
	nginx: "nginx",
	nim: "nim",
	nims: "nim",
	nix: "nix",
	patch: "diff",
	phtml: "php",
	php: "php",
	pl: "perl",
	pm: "perl",
	postcss: "postcss",
	pp: "puppet",
	prisma: "prisma",
	proto: "protobuf",
	ps1: "powershell",
	psm1: "powershell",
	pug: "pug",
	py: "python",
	pyi: "python",
	pyw: "python",
	r: "r",
	raku: "text",
	rb: "ruby",
	regex: "regexp",
	rs: "rust",
	sass: "sass",
	scala: "scala",
	scss: "scss",
	sh: "shellscript",
	sol: "solidity",
	sql: "sql",
	styl: "stylus",
	stylus: "stylus",
	svelte: "svelte",
	swift: "swift",
	tcl: "tcl",
	tex: "latex",
	tf: "terraform",
	tfvars: "hcl",
	toml: "toml",
	ts: "typescript",
	tsv: "tsv",
	tsx: "tsx",
	twig: "text",
	vim: "vim",
	vue: "vue",
	xml: "xml",
	xsl: "xml",
	xslt: "xml",
	yaml: "yaml",
	yml: "yaml",
	zig: "zig",
	zsh: "shellscript",
};

const FILENAME_TO_LANGUAGE: Record<string, string> = {
	Brewfile: "ruby",
	"CMakeLists.txt": "cmake",
	Capfile: "ruby",
	Dangerfile: "ruby",
	Dockerfile: "dockerfile",
	Gemfile: "ruby",
	Guardfile: "ruby",
	Makefile: "make",
	Rakefile: "ruby",
	Vagrantfile: "ruby",
	dockerfile: "dockerfile",
	makefile: "make",
};

/** Detected languages that always load through the highlighter. */
export const PLAIN_LANGUAGES = new Set(["text", "ansi"]);

const LANGUAGE_ALIASES: Record<string, string> = {
	bat: "bat",
	bash: "shellscript",
	clj: "clojure",
	cljc: "clojure",
	cljs: "clojure",
	coffee: "coffeescript",
	ex: "elixir",
	exs: "elixir",
	erl: "erlang",
	hrl: "erlang",
	fs: "fsharp",
	fsi: "fsharp",
	fsx: "fsharp",
	hs: "haskell",
	lhs: "haskell",
	js: "javascript",
	jl: "julia",
	kt: "kotlin",
	kts: "kotlin",
	md: "markdown",
	pl: "perl",
	pm: "perl",
	proto: "protobuf",
	ps1: "powershell",
	psm1: "powershell",
	py: "python",
	rb: "ruby",
	sh: "shellscript",
	sol: "solidity",
	styl: "stylus",
	tex: "latex",
	tf: "terraform",
	tfvars: "hcl",
	ts: "typescript",
	yml: "yaml",
	zsh: "shellscript",
};

/**
 * Resolve a detected language to a shiki id whose grammar can be loaded;
 * anything without a grammar falls back to plain text.
 */
export function resolveLanguage(language: string): string {
	const aliased = LANGUAGE_ALIASES[language] ?? language;
	return grammarLoaderFor(aliased) !== null || PLAIN_LANGUAGES.has(aliased) ? aliased : "text";
}

export function languageForFileName(fileName: string): string {
	if (FILENAME_TO_LANGUAGE[fileName] !== undefined)
		return resolveLanguage(FILENAME_TO_LANGUAGE[fileName]);
	const compound = fileName.match(/\.([^/\\]+\.[^/\\]+)$/)?.[1];
	if (compound !== undefined && EXTENSION_TO_LANGUAGE[compound] !== undefined) {
		return resolveLanguage(EXTENSION_TO_LANGUAGE[compound]);
	}
	const extension = fileName.match(/\.([^.]+)$/)?.[1] ?? "";
	return resolveLanguage(EXTENSION_TO_LANGUAGE[extension] ?? "text");
}

export function grammarLoaderFor(language: string): GrammarLoader | null {
	if (PLAIN_LANGUAGES.has(language)) return null;
	return GRAMMAR_IMPORTS[language] ?? null;
}

export function supportedLanguages(): string[] {
	return Object.keys(GRAMMAR_IMPORTS);
}
